# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
target 'HelloWorld' do
    # react native
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTBlob',
        'RCTCameraRoll',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
    ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-config', :path => '../node_modules/react-native-config'
    pod 'Sentry', '3.12.4'

    target 'HelloWorldTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
